{{- $externalMessaging := pluck "enabled" .Values.global.messaging.external .Values.messaging.external | compact | first }}
{{- $messagingUrl := pluck "url" .Values.global.messaging .Values.messaging | compact | first }}
{{- if $externalMessaging }}
{{- $messagingUrl = pluck "url" .Values.global.messaging.external .Values.messaging.external | compact | first | default $messagingUrl }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-configmap
data:
  {{- if $messagingUrl }}
  messaging.url: {{ $messagingUrl | quote }}
  {{- else }}
  messaging.host: {{ pluck "host" .Values.global.messaging.external .Values.messaging.external | compact | first | default .Values.messaging.host | quote }}
  messaging.amqp.port: {{ pluck "port" .Values.global.messaging.external.amqp .Values.messaging.external.amqp | compact | first | default .Values.messaging.amqp.port | quote }}
  {{- end }}
  {{- if not $externalMessaging }}
  messaging.enabled_plugins: |-
    {{ .Values.messagingService.messaging.plugins.enabled }}
  messaging.rabbitmq.conf: |-
    {{- include "messaging-rabbitmq.rabbitmq.conf" (dict "global" .Values.global "messagingService" .Values.messagingService) | nindent 4 }}
  {{- end }}
